### ISSUE TITLE
Test project doesn't run

### ISSUE THREAD

**Issue by ssuchanowski** [cypreess/django-getpaid#120]
Hey,

While doing `python manage.py migrate` I am getting this:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/djcelery/models.py", line 16, in <module>
    from . import managers
  File "/Users/ssuchanowski/Downloads/django-getpaid-master/getpaid_test_project/myvenv/lib/python3.6/site-packages/djcelery/managers.py", line 18, in <module>
    from celery.utils.timeutils import maybe_timedelta
ModuleNotFoundError: No module named 'celery.utils.timeutils'
```

Am I missing something?

**Comment by lukaszbanasiak** [comment]
This is causing Celery > 4.x. Had same issue and solved this here https://github.com/cypreess/django-getpaid/pull/121/commits/55a317e4f8da7b08d42fdb86e826a1d5a5b42973

**Comment by dekoza** [comment]
No longer an issue in upcoming 1.8 release.
