### ISSUE TITLE
Test project on Django 2.0

### ISSUE THREAD

**Issue by Piecio** [cypreess/django-getpaid#122]
Hi. On Django 1.8 everything works ok,  but on Django 2.0 when I select payment gateway and click continune I am getting this:

Traceback (most recent call last):
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\urls\resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\urls\resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\urls\resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "G:\python\getpaid_test_project\getpaid_test_project\urls.py", line 11, in <module>
    url(r'', include('getpaid.urls')),
  File "G:\python\getpaid_test_project\env\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "g:\python\getpaid_test_project\env\src\django-getpaid\getpaid\urls.py", line 15, in <module>
    include(urls, app_name=app_name, namespace=backend_namespace)
TypeError: include() got an unexpected keyword argument 'app_name'

**Comment by Piecio** [comment]
Ok, on Django 2.0 app_name was removed from the list of arguments of the include function.
Fix: In django-getpaid\getpaid\urls.py

change:

    backend_url = url(
        backend_url_regex,
        include(urls, app_name=app_name, namespace=backend_namespace)
    )

to:

    backend_url = url(
        backend_url_regex,include(
            (urls, app_name),
            namespace=backend_namespace,)
        )

**Comment by dekoza** [comment]
I included this in upcoming 1.8 release.
